### ISSUE TITLE
looks the same as the G29 codes

### ISSUE THREAD

**Issue by webr3** [joeroback/racechrono-canbus#1]
the main point, you may find this useful - stumbled on this whilst researching somebody else doing the same but with G29/J29 and feeding racecapture
- https://thesecretingredient.neocities.org/bmw/can/g29/
- credit to user on github https://github.com/jcevanco

I've been reading your posts over the web, to basically try and do the same and gather some metrics for track use, going to start getting a working setup on my daily g01, then on to an F20 b58 after I acquire one in the spring - think I'll go with a CSS Electronics CL2000 + their passive crocodile clip to start getting data out, then use the same approach as you.

discussion: how are you finding racechrono? it looks great, but I'm already frustrated by the requirement of BLE rather than a usb driver or enet straight in to a device, struggling to find an alternative for real time rather than post analysis (where we can just transform data) - right now I know I'll be comfortable doing the transformations, decode and recode in to any media type, but which software to ultimately use to review gps+camera+throttle/brake/steering etc is throwing me a bit, they're all very closed, unless you can enlighten or suggest?

**Comment by joeroback** [comment]
on interesting on https://thesecretingredient.neocities.org/bmw/can/g29/ .. there are a few in there i don't have and i have a few not listed.

My list: https://docs.google.com/spreadsheets/d/1O491j8jlEOYR6voFPAYZ2NpbNyCKAgqbxt4HVw0bSDA/edit#gid=1239910575

that being said, i sold my g80 and purchased a 992 GT3, thus https://github.com/joeroback/racechrono-canbus/tree/992_GT3

---

i really like racechrono, tho porsche's track precision app also seems great and somehow porsche is allowed on carplay, unlike racechrono, as apple's carplay terms of use explicitly has displaying real-time telemetry or car data is not allowed... if racechrono could be on carplay showing the deltas on the built-in screen like porsche, that would be amazing.

i haven't really found BLE to be an issue data at 50hz or less with newer iPhones and ESP32-S3 (dual core, so i dedicate one core to BLE stack). BLE is also what racebox mini uses, and i like that BLE is connectionless, so i find at the track and i can get in and out of the car and each time i get back in and go, things just work, don't have to fuss with the bluetooth settings and try and keep things "connected"

my setup is basically, iphone, racebox mini (25hz gps), esp32-s3 (can-bus), OBDLink MX+, gopro hero10+ and i find that racechrono manages all of this pretty gracefully, because i dont want to spend time with stupid tech while i am trying to drive.

i was using the MX+ for some fuel and oil/coolant temps, etc, i didn't have, but those are now listed on https://thesecretingredient.neocities.org/bmw/can/g29/ :)

afterwards, if i want to analyze laps, i just airdrop sessions from iphone to ipad pro and have a nice large screen go through laps. i have tried using AIM stuff, like RaceStudio3 and its definitely more pro, but i am not a pro and i find racechrono is a good balance between ease of use and information.

---

TrackAddict was a WiFi based standard, which is interesting, but i find that TrackAddict and RaceRender products are EOL and haven't been updated in years. 

Numeric Broadcast Protocol (NBP) Devices: https://racerender.com/TrackAddict/docs/Interop.html#NBP

which is similar to RaceChrono's DIY BLE concept

**Comment by webr3** [comment]
Congrats on the GT3, would love to see it, I've got a track day in one coming up in 2 weeks and quietly intimidated by the thought!

At this point I'm sold on the racebox mini + go pro, hence landing on race chrono, then finally your posts/repos. OBDLink MX+ keeps coming up and if it's working for you I'm sold, as have a strong preference for "just works" - although I may try the MHD adapter first as being able to have one device that also let's me flash different tunes / revert to stock easily appeals somewhat.

Thanks for taking the time, and for all your write ups + photos, seeing someone else get in to a g series with a simple wire out from the pt-bus - without making a mess of the interior - really pushed me in to investigating things further, your work was invaluable here.

The only bit I'm not sold on yet is the PT-CAN interface itself, those Contactless CAN Bus Reader interfaces from CSS electronics + their CL2000 appeal somewhat in not having to break out soldering irons or dive in to anything too custom, or indeed leave a mark after whilst testing.

**Comment by joeroback** [comment]
if i was doing any OBD2 stuff again, i would probably go with the Kiwi3, as its BLE as well, the MX+ is regular bluetooth and you do have to fuss with it connecting sometimes.

for both the g80 and gt3, i just used posi-tap connectors, contactless was appealing, but saw too many posts of contactless stuff losing connection, so posi-tap stuff was good middle ground, solid connection and i didn't have to mess with any wiring harnesses, etc.

https://www.amazon.com/gp/product/B004D0C2RC/

https://photos.app.goo.gl/6pPrfQHHsmmdqfCz7

**Comment by joeroback** [comment]
for testing, i was using a raspberry pi4 + can hat + anker battery to use can-utils and candump for logging and later offline decoding of PIDs

https://photos.app.goo.gl/pTZU7J7taPfTp4q6A

i covered the wire in a black nylon sleeve and had a quick disconnect to go from pi4 to esp32 depending if i was debugging/decoding or at the track

**Comment by webr3** [comment]
part conversation, part notes for any one who hits this in the future and finds via search:

> if i was doing any OBD2 stuff again, i would probably go with the Kiwi3, as its BLE as well, the MX+ is regular bluetooth and you do have to fuss with it connecting sometimes.

thanks, did some digging through since kiwi 3/4 are discontinued now, comparing the OBDLink devices the OBDLink CX (bmw compatible, implements ISO 11898) is Bluetooth 5.1 BLE, so going to give this a punt.

> saw too many posts of contactless stuff losing connection, so posi-tap stuff was good middle ground
mind if I ask where you say posts about the contactless losing connection, got a feeling I'm missing a couple of good forums to check as haven't seen it mentioned much on racechrono, bimmerpost etc

again thanks for sharing all your insights!

**Comment by joeroback** [comment]
hrm, i don't remember, it was mainly around the Racelogic VBOX, which has an induction option on the porsche forums (rennlist.com) .. it seemed hit or miss. the other thing with the induction, you need to have a decent run of the twisted pair untwisted to get it in the induction case, which usually means you have to pull the wires out of the harness to untwist and i didn't want to do that, posi-tap can sneak in easily IMO.

992 GT3, very similar CAN connection in passenger footwell like G80:
https://share.icloud.com/photos/00fneWRfEROZ56_T70gzRw6pg

**Comment by joeroback** [comment]
oh i didn't realize kiwi products were discontinued.. well my experience with OBDII was < 3hz once you add 3 or 4 items, so with that list you posted here, there is nothing unique to OBDII data, its all available on can bus, at least for F/G series BMW and equivalent toyotas.

in any case, i am still having issues getting any data from the 992, even though it seems plenty of ppl using VBOX on rennlist with the same CAN bus wires.. will need a weekend or more to really debug. lol

**Comment by webr3** [comment]
honestly joe, I've never seen a space so locked in proprietary hell, with anybody who makes any progress just making the situation worse by trying to profit.

the basic principles are very simple, data flying over a bus you can leach in to, just needs a simple uniform reader, a community providing decode maps, then a well defined interchange format for the translated data back out, then some hardware/software vendors who are willing to both import and export it.

I'm surprised we even need to have this discussion over use cases so common and obvious that they should have been solved a decade or two ago, especially considering the industry size.

Keep hitting the same forums and conversations over and over, rennlist, bimmerpost, a few software related forums, and the same people asking the same questions and going down the same dead ends or giving up and going proprietary with vendor lock in.

**Comment by joeroback** [comment]
added support for extra PIDs from https://thesecretingredient.neocities.org/bmw/can/g29/ in https://github.com/joeroback/racechrono-canbus/commit/db9a3d0ac0cd22e483c185296464cb4d84b81210
